export enum NotificationTypeEnum {
  TAGGED_IN_POST = 'Tagged in post',
  TAGGED_IN_COMMENT = 'Tagged in comment',
  COMMENT_ON_POST = 'Comment on post',
  REPLY_TO_COMMENT = 'Reply to comment',
  REVIEW_ON_PROFILE = 'Review on profile',
  COMMENT_ON_REVIEW = 'Comment on review',
  REPORT_PROCESSING = 'Report processing',
  REPORT_PROCESSED = 'Report processed',
  MODERATION_RECEIVED = 'Moderation received',
  MESSAGE = 'Message',
  QUEUE_APPLICATION = 'Queue application',
  QUEUE_APPLICATION_ACCEPTED = 'Queue application acceptance',
  QUEUE_CLOSED = 'Queue closed',
  LOST_NEAR_LOCATION = 'Lost near location',
  FOUND_NEAR_LOCATION = 'Found near location',
  RESCUE_NEAR_LOCATION = 'Rescue near location',
  SUGGESTED_DONATION = 'Suggested donation',
  SUGGESTED_RESCUE = 'Suggested rescue',
  SUGGESTED_FOSTER = 'Suggested foster',
  SUGGESTED_ADOPTION = 'Suggested adoption',
  ALERT = 'Alert',
  PROMOTION = 'Promotion',
  ANNOUNCEMENT = 'Announcement',
  MISCELLANEOUS = 'Miscellaneous',
}
